### ISSUE TITLE
模板引擎标签

### ISSUE THREAD

**Issue by zuoyanart** [livisky/liblog#1]
看了您的模板标签，和bootstrap函数。 这样走的话，多个获取文章list的标签，不都变成同步了吗？ 这样nodejs的优势是不是就减弱了？

**Comment by livisky** [comment]
效率是会差点，主要是考虑模版修改及调用方便，后续可以通过其他方式弥补，譬如缓存数据等。

**Comment by zuoyanart** [comment]
从可用性上来讲，学习一个模板引擎语法，和学习一下node的函数调用，难度基本一样了。如果通过其他方式增强性能，是不是同时也增加了程序架构和二次开发的复杂度了？个人感觉还是不要这样设计为好。还有这种理念上的事能让人说句话再关闭吗？

**Comment by livisky** [comment]
左兄的建议我会考虑的。话说添加cms标签语法是不是也多了一种选择呢，有些人不喜欢去改调用代码，直接就标签能循环出来就好了就跟dedecms一样。当然愿意二次开发的人，还是可以用nodejs本身的方式写controller调用。

**Comment by zuoyanart** [comment]
好的
